# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './functions'
    verbose: true
  displayName: 'Install npm packages'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './functions'
    customCommand: 'run lint'
  displayName: "Lint"
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './functions'
    customCommand: 'run build --verbose'
  displayName: "Build"
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './functions'
    customCommand: 'run test -- --reporters="default" --collectCoverage --coverageReporters=cobertura'
  displayName: "Test"
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/functions/coverage/cobertura-coverage.xml'
- task: CopyFiles@2
  inputs:
    Contents: |
      **/functions/lib/**
      **/functions/node_modules/**
      **/functions/package.json
      firebase.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: "Copy artifact files"
- task: CopyFiles@2
  inputs:
    Contents: |
      **/functions/package.json
      **/functions/Deploy.ps1

    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
  displayName: "Copy package.json"
# - task: Npm@1
#   inputs:
#     command: 'publish'
#     workingDir: '$(Build.ArtifactStagingDirectory)'
#     publishRegistry: 'useFeed'
#     publishFeed: 'b976c137-b275-4fee-9ccb-2c4e0fcbbe86/90d3fc13-d675-4452-b387-0298f9621eff'
